global:
  # Important to note, that scrape times > 5minutes can't be handled
  # by grafana gracefully and will be treated as scarce metrics
  scrape_interval:  1m 
  scrape_timeout: 60s

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9090

- job_name: flight-exporter
  metrics_path: /metrics
  static_configs:
    - targets:
        - 'flight-exporter:10019'
