{
 "title": "Flights",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Flight Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flight_ground_speed", "legendFormat": "{{callsign}}" }
   ]
  },
  {
   "title": "Flight Altitude",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "flight_altitude", "legendFormat": "{{callsign}}" }
   ]
  },
  {
   "title": "Aircraft Overhead",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "targets": [
    { "expr": "aircraft_overhead", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flightpath Heatmap",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "flight_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Destination Airports",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "flight_info{destination_airport_name!=\"N/A\"}",
     "legendFormat": "{{destination_airport_name}}"
    }
   ]
  },
  {
   "title": "Recent Flights",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "flight_info", "legendFormat": "__auto" }
   ]
  }
 ]
}